# Generated by Django 5.0.6 on 2024-07-03 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='court',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.location'),
        ),
    ]
